% RunAllPFFits
%
% Run all the PF fits

%% Initialize
clear; close all;

%% 2020-01-31
%
% 7x9 stimulus
% 
% 11043, 0 and 0.05D defocus at 7 mm pupil.
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.00,'pupilDiam',7,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'computationalName','7_9_0');

% 11046, 0.05D and 0.10D at 7 mm pupil
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'computationalName','7_9_0');

fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7,'computationalName','7_9_0');

% Same fits with decr scaling
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.00,'pupilDiam',7,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7,'computationalName','7_9_0');

%% 2021-09-14
%
%  7x9 stimulus replication
fitThresholdContourIncrDecrData('subj','11046','dataDate','20210914','subProject','IncrDecr2','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20210914','subProject','IncrDecr2','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20210914','subProject','IncrDecr2','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20210914','subProject','IncrDecr2','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7,'computationalName','7_9_0');

%% 2021-10-18
%
%  5x7 stimulus
% fitThresholdContourIncrDecrData('subj','11046','dataDate','20211018','subProject','IncrDecr3','condition','Size_2', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
%     'defocusDiopters',0.05,'pupilDiam',7,'theLim',4);
% fitThresholdContourIncrDecrData('subj','11046','dataDate','20211018','subProject','IncrDecr3','condition','Size_2', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
%     'defocusDiopters',0.10,'pupilDiam',7,'theLim',4);
% fitThresholdContourIncrDecrData('subj','11046','dataDate','20211018','subProject','IncrDecr3','condition','Size_2', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
%     'defocusDiopters',0.05,'pupilDiam',7,'theLim',4);
% fitThresholdContourIncrDecrData('subj','11046','dataDate','20211018','subProject','IncrDecr3','condition','Size_2', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
%     'defocusDiopters',0.10,'pupilDiam',7,'theLim',4);

%% 2021-10-26
%
%  5x7 stimulus
% fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_2', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
%     'defocusDiopters',0.05,'pupilDiam',7,'theLim',4);
% fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_2', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
%     'defocusDiopters',0.10,'pupilDiam',7,'theLim',4);
% fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_2', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
%     'defocusDiopters',0.05,'pupilDiam',7,'theLim',4);
% fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_2', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
%     'defocusDiopters',0.10,'pupilDiam',7,'theLim',4);

%% 2021-10-26
%
%  6x8 stimulus
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_4', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'theLim',2,'computationalName','6_8_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_4', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7,'theLim',2,'computationalName','6_8_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_4', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'theLim',2,'computationalName','6_8_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_4', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7,'theLim',2,'computationalName','6_8_0');

%% 2021-10-26
%
%  7x9 stimulus
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'theLim',2,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7,'theLim',2,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'theLim',2,'computationalName','7_9_0');
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211026','subProject','IncrDecr4','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7,'theLim',2,'computationalName','7_9_0');

%% 2021-11-23
%
%  7x9 stimulus, separation 0.  These were just measured at 315 degs, so we
%  can't scale decr or scale to other sessions.
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211123','subProject','IncrDecr5','condition','Size1_Sep0', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7,'theLim',2,'computationalName','7_9_0','pfSlope',12);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20211123','subProject','IncrDecr5','condition','Size1_Sep0', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7,'theLim',2,'computationalName','7_9_0','pfSlope',12);


