% RunAllPFFits
%
% Run all the PF fits

%% 2020-01-31
%
% 7x9 stimulus
% 
% 11043, 0 and 0.05D defocus at 7 mm pupil.
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.00,'pupilDiam',7);
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7);

% 11046, 0.05D and 0.10D at 7 mm pupil
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7);

% Same fits with decr scaling
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.00,'pupilDiam',7);
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7);

%% 2021-09-14
%
%  7x9 stimulus replication
fitThresholdContourIncrDecrData('subj','11046','dataDate','20210914','subProject','IncrDecr2','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20210914','subProject','IncrDecr2','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20210914','subProject','IncrDecr2','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05,'pupilDiam',7);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20210914','subProject','IncrDecr2','condition','Size_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10,'pupilDiam',7);

