% RunAllPFFits
%
% Run all the PF fits

% Basic fits, no decr scaling
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',false,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05);

% Basic fits, with decr scaling
fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.05);
fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
    'norm',false','corrGuess',true,'reflIn',false,'reflOut',false,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true, ...
    'defocusDiopters',0.10);

% Reflect out, with decr scaling
% fitThresholdContourIncrDecrData('subj','11043','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',true,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true);
% fitThresholdContourIncrDecrData('subj','11046','dataDate','20200131','subProject','IncrDecr1','condition','Separation_1', ...
%     'norm',false','corrGuess',true,'reflIn',false,'reflOut',true,'scaleDecr',true,'constrainedSlopeFits',true,'lockSlope',true);


